--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: pokedex-front
  name: pokedex-front
  namespace: dev
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: pokedex-front
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: pokedex-front
    spec: 
      containers: 
        - 
          image: "registry.lab.amrcloud.local/amrcloud/pokedex-front:latest"
          imagePullPolicy: Always
          name: pokedex-front
          ports: 
            - 
              containerPort: 3000
          resources: 
            limits: 
              cpu: 1024m
              memory: 512Mi
            requests: 
              cpu: 500m
              memory: 256Mi
      imagePullSecrets: 
        - 
          name: regcred